import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";
import {ClerkProvider} from '@clerk/nextjs';

const mont = Montserrat({
  subsets: ["latin"],
  weight: ['300','600','400'],
  variable: '--font-montserrat',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={mont.variable}>{children}</body>
    </html>
    </ClerkProvider>
  );
}